### ISSUE TITLE
Prompts for Annotated Test Set

### ISSUE THREAD

**Issue by forest-snow** [microsoft/TOXIGEN#14]
Awesome work! 

I noticed the annotated test set (792 examples) doesn't have the original prompts for each generated text. Could that be found anywhere?

Thanks!

**Comment by Thartvigsen** [comment]
Thanks for your interest in our work! Sadly, we don't have the exact (prompt, response) pairs, but you can find the set of all the prompts we used [here](https://github.com/microsoft/TOXIGEN/tree/main/prompts).
