### ISSUE TITLE
KeyError: 'choices'

### ISSUE THREAD

**Issue by PhanVanVien** [microsoft/TOXIGEN#15]
First of all let me thank your research team. And sorry if I don't speak English very well. I'm very interested in your research but I have one error when running on both jupyter and notebook. 
![image](https://user-images.githubusercontent.com/84467489/217283759-8b458315-8f52-497a-9a0b-4905f4e2cef6.png) 
Looking forward to your reply. Thank you.

**Comment by Thartvigsen** [comment]
Hello, could you `print(output)` and show what it returns?

**Comment by PhanVanVien** [comment]
Thanks for your reply and here is the result
![image](https://user-images.githubusercontent.com/84467489/217299662-c9de352c-891b-40b5-a80a-fde3fb98740d.png)

**Comment by Thartvigsen** [comment]
Could you show the output that's returned when you `print(output)`? And I assume you've got your API key from OpenAI set up?

**Comment by PhanVanVien** [comment]
I'm sorry if my answer is not right for your question

1. I can't print by this way whether the print method you said I should look for ? I just go to the file /usr/local/lib/python3.8/dist-packages/toxigen/language_models.py and add print(output) but no output.
![image](https://user-images.githubusercontent.com/84467489/217408762-0203ee99-f920-457e-8672-6ea427fc4f05.png)

2. I checked the requests but it didn't come up with a viable result
![image](https://user-images.githubusercontent.com/84467489/217409214-8571e678-4698-4b58-b005-36c4074d6b02.png)

3. 
With Invalid Key (I removed a stream of key) 
![image](https://user-images.githubusercontent.com/84467489/217409551-1b08da7c-ba5f-40d0-a4c7-223c1e47edb2.png)
Result is Error

With Valid Key (I hide my key for secret)
![image](https://user-images.githubusercontent.com/84467489/217410062-16c860bb-42f0-459b-8d03-d75cf99697f0.png)
Does this mean my key is working properly ?

4. And this code only works with roberta. I read about this in #8
![image](https://user-images.githubusercontent.com/84467489/217410567-9a3f2098-9c63-450d-82e2-86b0c307a1fb.png)
Thank you.

**Comment by PhanVanVien** [comment]
![image](https://user-images.githubusercontent.com/84467489/217418219-4faa14bc-2ee0-44fc-9a18-0c861c3399ad.png)
When i call function call.

**Comment by PhanVanVien** [comment]
1. I try with url = "https://api.openai.com/v1/engines/text-ada-001" and response = requests.get(url, headers=headers) (get method)
![image](https://user-images.githubusercontent.com/84467489/217430470-3cc83510-78b8-4e5d-9efc-2c8a711cba38.png)
and result:
![image](https://user-images.githubusercontent.com/84467489/217430537-c2de1901-267d-43f2-b7a1-7a98dcd49b4b.png)

2. I try with url = "https://api.openai.com/v1/engines/text-ada-001/completions" or response = requests.post(url, headers=headers) (post method and without  json=data)/response = requests.get(url, headers=headers, json=data)
![image](https://user-images.githubusercontent.com/84467489/217431726-2723de5d-4f96-4d64-a6e2-952f914caedc.png)

Thank you.

**Comment by PhanVanVien** [comment]
I look forward to your response.

**Comment by Thartvigsen** [comment]
It looks like one of the errors shows that you have exceeded your quota for GPT-3 api calls?

![image](https://user-images.githubusercontent.com/26936677/217826355-5823bd5e-095e-4588-b98b-744209888233.png)

**Comment by PhanVanVien** [comment]
Could you check again with your secret API key one time? And Do you pay to use? Because I remember that it's free on this time, especially this my new account and I don't use anything before.

**Comment by PhanVanVien** [comment]
yes i get it. Thank you for your interesting work and quick responses from you. Sad to not be able to access it anymore.

**Comment by PhanVanVien** [comment]
Thank you very much.
