### ISSUE TITLE
IndexError: list index out of range when running alice

### ISSUE THREAD

**Issue by zqypku** [microsoft/TOXIGEN#22]
Hi, 
When I ran alice by `python generate.py --input_prompts <path_to_prompt_file.txt> --language_model GPT3 --ALICE True --classifier HateBERT --output-file <path_to_output_file.txt> --openai_api_key <your_api_key>`, I got an index error as shown in the figure. 
<img width="1013" alt="Screenshot 2023-06-15 at 13 21 19" src="https://github.com/microsoft/TOXIGEN/assets/71053864/20889faf-8275-4de2-b575-369b8167f954">

Previously, I also got index error in File "toxigen/alice.py", line 130 `scores_ = torch.Tensor([[[omit_(full_names[i][0][j], scores[i][0][j], stops, prompt) for j in range(len(scores[i][0]))]] for i in range(num_beams)])`.
And I find that there are some blank list in `full_names` and `scores`, here is an example when we get `full_names`:

[[], [], [], [[' without', ' in', ' that', ' with', ' where']], [[' Together', ' together', ' in', ' moving', ' up']], [[' United', ' reason', ' U', ' only', ' very']], [[' the', ' potential', ' their', ' what', ' how']], [[' another', ' any', ' if', ' anymore', ' here']], [['!', '.', '\n', ' and', ' .']], [[' is', ' are', ' can', ' will', ' may']]]   

We can see that the first three are blank lists.
I wonder if there are any hyperparameters that can control the output from the GPT3 API not to return such blank things.
Or if there are any ways to prevent this from happening.
Can you help me with this?

**Comment by Thartvigsen** [comment]
I believe these errors stem from changes in the GPT3 API. At this point, I don't personally have access to the API so I'm not positive what has actually changed. It might be possible to just drop empty lists because GPT3 may just return end tokens sometimes and stop generating immediately? I suggest also investigating what ```outputs``` contains.. it may be that ```outputs['choices'][0]['logprobs']['top_logprobs'][0]``` doesn't return the top log probs if the api has changed.

**Comment by zqypku** [comment]
Thanks for your reply!
As I have successfully run alice with some prompts, `outputs['choices'][0]['logprobs']['top_logprobs'][0]` should return successfully. Thus I agree that this may be caused by GPT3 just returning end tokens sometimes and stop generating immediately. I will check the API and see if there are any solutions. :D

**Comment by Thartvigsen** [comment]
If you find a solution, please either submit a pull request or provide instructions! I'd love to have this cleared up for others, too!

**Comment by zqypku** [comment]
Ok. :D

**Comment by zqypku** [comment]
Hi, I tried several times and find that this may be caused by the instability of API, which returns the `dict` but contains nothing. So we just need to know whether the server returns something. Otherwise, one more trial is needed.
