### ISSUE TITLE
Warning - Legal and Ethical Issue for using this dataset - Issues could stem from political activism being built into algorithms

### ISSUE THREAD

**Issue by masalai75** [microsoft/TOXIGEN#28]
On reviewing the Toxigen Machine Learning algorithm and its associated dataset, as hosted on github. While I appreciate the effort to address and measure bias in language models, I'd like to raise some concerns regarding the current approach to demographic representation in your dataset.

Firstly, the dataset seems to overlook the inclusion of specific demographic groups, notably individuals of Caucasian descent and males. This omission is noteworthy as it potentially introduces a form of selection bias. By not representing these groups, the algorithm may inadvertently reinforce the misconception that bias and discrimination are issues exclusive to non-Caucasian and non-male populations. However, in a global context, any demographic group can be a minority, and their experiences and perspectives are essential in understanding and addressing bias comprehensively.

To enhance the robustness of your approach, I would recommend expanding the dataset to include a broader spectrum of demographic groups. This expansion would allow for a more holistic assessment of biases across different populations. Additionally, integrating a mechanism for the algorithm to recognize and classify a diverse range of groups would further refine its accuracy in gauging biases.

Furthermore, I suggest considering the iTo enhance the robustness of your approach, I would recommend expanding the dataset to include a broader spectrum of demographic groups. This expansion would allow for a more holistic assessment of biases across different populations. Additionally, integrating a mechanism for the algorithm to recognize and classify a diverse range of groups would further refine its accuracy in gauging biases.
mplementation of intersectional analysis in your model. This approach could provide deeper insights into how overlapping identities (such as race, gender, socioeconomic status) contribute to unique experiences of bias and discrimination.

Your project has the potential to make significant contributions to the field of ethical AI. By broadening the scope of demographic representation in your dataset, the Toxigen algorithm can become a more inclusive and effective tool in identifying and mitigating biases in language models.

Care should be taken using this dataset, as it has problems with its classification system that could open the user up to lawsuit, in many US states, and likely many nations.
Its problem stems from being a proudly activist dataset, that builds in bias as a feature. So instead of trying to eliminate all biases from the authors classification method, the author has gone out of their way to include DEI and bias into the very core of the detection method used in Toxigen. The authors have been specific in that white people can never be the target of hate speech (unless of course they fit into another intersectional category.

Thank you for your dedication to this important work, and I look forward to seeing how your project evolves.

**Comment by Thartvigsen** [comment]
Hi @masalai75 thanks for your comments!

Please feel free to contribute to the literature by extending our work as you see fit. Adding more demographic groups is indeed an area of future work. You are welcome to contribute new data sources or provide links to other existing datasets. I do strongly suggest informing your work with a literature review on the impacts of societal power dynamics on harmfulness of language alongside the impacts of historical marginalization. As it stands, your feedback is not applicable to general users, and legality concerns are hypothetical (please review the license). So this issue will be closed. Thank you again for your interest in our work!

**Comment by wassname** [comment]
I think the issues of racial discrimination in the dataset design and paper seem pretty clear and intentional to me. 

> Our ultimate aim is to shift power dynamics to targets of oppression. Therefore, we do not consider identity dimen- sions that are historically the agents of oppression (e.g., whiteness, heterosexuality, able-bodied-ness).

The authors of this paper represent a set of institutions, and I'm not sure if this complies with their policies. Or with GitHub's, or Huggingface's.

This has also been flagged on the huggingface platform: https://huggingface.co/datasets/skg/toxigen-data/discussions/6

**Comment by masalai75** [comment]
@Thartvigsen  Isnt Gemini are warning against over zealous activism being introduced into the guard rails?  Toxigen is courting the same kind of negative attention, and I hope developers will think twice before using it in its current form.  Double standards on labeling data need to be removed otherwise some users are going to end up in a lawsuit or financial penalties.

**Comment by wassname** [comment]
Yeah I would encourage people to look at datasets like RealToxicityPrompts which is used in the [LLM Safety Leaderboard](https://huggingface.co/spaces/AI-Secure/llm-trustworthy-leaderboard). It's older, but good, it just looks at the real world frequency of toxicity (on reddit), without the racist activism in toxigen. A pretty reasonable and fair design that captures the weirdness and diversity of toxic speech.

**Comment by masalai75** [comment]
Im not particularly fond of anecdotes, as you can always find the reverse, but this one is quite appropriate just to show how far people will go in making excuses when things are reversed.   When you have commentators saying that "white bastard" is not racist straight faced, then your system is worthless, or more so dangerous. https://www.smh.com.au/sport/is-white-bastard-racist-the-divided-reactions-to-sam-kerr-racism-allegation-20240307-p5fajg.html  @wassname Id like to see an Ai create filter, but stripped of identifiers.  So that white = black = asian etc, The kind of colorblind, neutral approach that has progressed us so far forward as a society, and is now in danger of being regressed.
