### ISSUE TITLE
Issue With prompt_label in Data

### ISSUE THREAD

**Issue by aflah02** [microsoft/TOXIGEN#3]
Hey
I was trying to separate out the toxic and benign samples but noticed something weird. All the values in the prompt_label column are 0 for some reason. Is this a mistake or am I missing something?

<img width="782" alt="image" src="https://user-images.githubusercontent.com/72096386/172068728-b508ab82-476f-46c9-a410-cebbbb4196df.png">
<img width="736" alt="image" src="https://user-images.githubusercontent.com/72096386/172068749-e773765e-b2d6-4155-ab26-a26cb864fdd3.png">

**Comment by sara-02** [comment]
I was able to reproduce the error and found that the prompt-label feature has all values as zero. One would expect them to be 0 or 1 depending on the toxic and non-toxic prompts.

**Comment by Thartvigsen** [comment]
This is resolved now, issue with the data loader in huggingface
