### ISSUE TITLE
Toxigen metric not generating anything

### ISSUE THREAD

**Issue by mario-mgmn-bsc** [microsoft/TOXIGEN#33]
Hi! I'm trying to analyse some of my model's generations using the regard promptset. When I try to apply the regard metric everything seems to work fine, but when I try to use the toxigen metric it doesn't return anything. Here's the command  I'm using:

`robbie/scripts/run_eval.sh --dataset regard --model ../my_model -s toxigen  --result-dir results/ --dataset-dir robbie/datasets/regard/`

And this is the output: 
`MetricResult(scores=[], stats={})`

Any help would be greatly appreciated. Thanks!

**Comment by Thartvigsen** [comment]
Hi @mario-mgmn-bsc thanks for your interest in our work! Could you clarify what "the toxigen metric" is, what `run_eval.sh` is? I don't quite understand how your issue relates to the ToxiGen repo.
