### ISSUE TITLE
Annotated data additional information inquiry

### ISSUE THREAD

**Issue by TheMrguiller** [microsoft/TOXIGEN#34]
Hi,

I would like to know if there is any possibility of obtaining the annotations from each worker in the test set. Right now, we have an aggregated value of the scores obtained in the annotation process, but I believe it would be interesting for the research community to have access to the disaggregated values. The new research wave on annotation disagreement is gaining significant attention. As one of the reference articles on implicit toxicity, providing this data would enhance your position in the field.

Thank you in advance,

**Comment by Thartvigsen** [comment]
@TheMrguiller this is a fantastic suggestion, thanks! I just confirmed we do actually have that data and I'll look into the process to get it released! I'll let you know when it's up

**Comment by TheMrguiller** [comment]
@Thartvigsen thank you for the quick response. It could also be particularly interesting to know the total number of annotators to grasp the diversity of opinions, and if available, to have information about demographics, gender, age, ethnicity, etc. I hope this would help future researchers in the field. The only downside is that only 3 annotators were involved in the annotation process of each comment. It would have been nice if someone extended the work to analyze this disagreement, to gather information on the ambiguity or complexity of the comment.

**Comment by Thartvigsen** [comment]
@TheMrguiller I've added the raw annotations to the ToxiGen huggingface page. You can load them directly from huggingface using `load_dataset("toxigen/toxigen-data", "annotations")`. We included the annotators' demographic data they uploaded and anonymized their Mechanical Turk IDs. Please let me know if you run into problems loading these data or have further questions!
