### ISSUE TITLE
Adding licensing info

### ISSUE THREAD

**Issue by mfrancesch10** [microsoft/TOXIGEN#6]
Hi! Would it be possible to add licensing info for the dataset as well as for code and models?
In particular, I'm interested in understanding if the dataset can be used in a commercial setting, in a research setting, whether and how attribution is required etc.
Thank you so much!!!

**Comment by Thartvigsen** [comment]
@mfrancesch10 we've seen this comment and will get back to you as soon as we can!

**Comment by mfrancesch10** [comment]
Thanks!!! :)

**Comment by hamidpalangi** [comment]
Hi @mfrancesch10 , you can find the license information in LICENSE.txt file under the main branch.
